### ISSUE TITLE
Running PyYAT for the first time

### ISSUE THREAD

**Issue by DJuego** [2vin/PyYAT#2]
Hello, Thank you for this project. I have a problem and a question.

The problem is that I can't execute the project. I am working on Windows 10x64 with Python Portable.

I install OpenCV with **pip install opencv-contrib-python** without problems.

I download the weights successfully from https://pjreddie.com/media/files/yolov3.weights

I get this error:

```
p:\Utilidades\Anotadores\PyYAT\PyYAT-master>python yolo_annotation_tool.py
Traceback (most recent call last):
  File "p:\Utilidades\Anotadores\PyYAT\PyYAT-master\yolo_annotation_tool.py", line 23, in <module>
    ob = recognize_objects("./models/yolov3.weights", "./models/yolov3.cfg","./models/coco.names")
  File "p:\Utilidades\Anotadores\PyYAT\PyYAT-master\recognize_objects.py", line 18, in __init__
    self.ln = [self.ln[i[0] - 1] for i in self.net.getUnconnectedOutLayers()]
  File "p:\Utilidades\Anotadores\PyYAT\PyYAT-master\recognize_objects.py", line 18, in <listcomp>
    self.ln = [self.ln[i[0] - 1] for i in self.net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
```

My question: is the generated YOLO format compatible with Yolov7?

Thank you in advance!

DJuego

**Comment by 2vin** [comment]
@partheee thanks for resolving the issue! I consider it solved now
