### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by jose-cisco** [2vin/PyYAT#8]
while i run the yolo_annotation_tool.py i got 
from recognize_objects import recognize_objects Exception has occurred: TabError
inconsistent use of tabs and spaces in indentation (recognize_objects.py, line 21)
  File "D:\PyYAT\yolo_annotation_tool.py", line 6, in <module>
    from recognize_objects import recognize_objects
TabError: inconsistent use of tabs and spaces in indentation (recognize_objects.py, line 21)
and then when i look on ur file it got some error man how can i used on it please help me out.

**Comment by mradul-kanugo** [comment]
@jose-cisco Open the file in any IDE and reformat code for yolo_annotation_tool.py file.

**Comment by 2vin** [comment]
@mradul-kanugo Thanks for resolving the issue.
